id: P008136
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG25852
  title: གཏམ་རྒྱུད་གཅེས་བཏུས།
  author: ''
  volumes:
    1bc42e154b5744868d1859298d091492:
      image_group_id: I1KG25854
      title: Volume 1 of gtam rgyud gces btus/
      volume_number: 1
      total_pages: 202
      base_file: v001.txt
ebook_metadata:
  title: གཏམ་རྒྱུད་གཅེས་བཏུས།
  author: ''
  sku: P008136
  cover: cover.jpg
  layers:
  - pagination
