id: P008136
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG25852
  title: གཏམ་རྒྱུད་གཅེས་བཏུས།
  author: ''
  volumes:
    045b443ca4c042d397aee06eed0e9486:
      image_group_id: I1KG25854
      title: ''
      volume_number: 1
      total_pages: 202
ebook_metadata:
  title: གཏམ་རྒྱུད་གཅེས་བཏུས།
  author: ''
  sku: P008136
  cover: cover.jpg
  layers:
  - pagination
